### Create a user
PUT http://localhost:3002/users
Content-Type: application/json
  {
    "username": "pablo",
    "email":"pablo@kvl.com",
    "password": "123456"
  }

### Get plataformas
GET http://localhost:3002/plataformas